[workspace]
resolver = "2"
members = ["macro-expander", "macro-expander-macro", "example-macro"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
authors = ["Techcable <git@techcable.net>"]
repository = "https://github.com/Techcable/macro-expander.rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
