[workspace]
resolver = "2"
members = ["example-macro", "macro-expander", "macro-expander-macro"]

[workspace.package]
version = "0.1.0"
authors = ["Techcable <git@techcable.net>"]
edition = "2021"
rust-version = "1.56"
readme = "README.md"
repository = "https://github.com/Techcable/macro-expander.rs"
license = "MIT OR Apache-2.0"
keywords = ["debug", "expander", "macro", "trace"]
categories = [
    "development-tools",
    "development-tools::debugging",
    "development-tools::procedural-macro-helpers",
]

[workspace.lints.clippy]
## groups ##

cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

# restrictions

redundant_test_prefix = "warn" # name test_foo is redundant with #[test] attr

# safety

multiple_unsafe_ops_per_block = "deny"
undocumented_unsafe_blocks = "deny"

## aggressively lint casts ##
# in an ideal world, overflowing casts would panic
# linting them (with deny) is the second best option

cast_lossless = "allow" # lossless casts are fine, lints will catch if types change
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_ptr_alignment = "deny"
cast_sign_loss = "deny"
char_lit_as_u8 = "deny"
fn_to_numeric_cast = "deny"
fn_to_numeric_cast_any = "deny"
fn_to_numeric_cast_with_truncation = "deny"
ptr_as_ptr = "allow" # pointer casts are fine as long as they don't violate another rule

# excessively pedantic (even for clippy::pedantic)

missing_panics_doc = "allow"
must_use_candidate = "allow"
needless_raw_string_hashes = "allow"
redundant_else = "allow"
too_many_lines = "allow"

[workspace.lints.rust]
missing_docs = "allow" # this is crate-specific
unsafe_op_in_unsafe_fn = "deny"

[workspace.metadata.cargo-reedme]
note = "Do not edit - automatically generated by cargo-reedme"
